sudo: required
language: node_js
node_js:
  - "10.16.3"
services:
  - docker
script: 'true'
before_install:
  - docker build -t srinisrinivas/frontend -f Dockerfile .

after_success:
  - docker build -t srinisrinivas/frontend .
  #push to docker hub
  - docker push srinisrinivas/frontend:first
# deploy: 
#     provider: elasticbeanstalk
#     region: "us-east-2"
#     app: "docker"
#     env: "Docker-env"
#     bucket_name: "elasticbeanstalk-us-east-2-423694414493"
#     bucket_path: "docker"
#     on:
#       branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: 
#         secure: "$AWS_SECRET_KEY"